### ISSUE TITLE
execute with ts-node

### ISSUE THREAD

**Issue by maosmurf** [ngx-universal/state-transfer#10]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[X] feature request
```

**Current behavior**
When executung an Angular4 App with `ts-node src/server.ts`, teh app crashes:

```
node_modules/@ngx-universal/state-transfer/src/state-transfer.service.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

**Expected/desired behavior**
App using state-transfer should be runnable directly via typescript.

**Minimal reproduction of the problem with instructions**
`ts-node src/server.ts`

**What is the motivation / use case for changing the behavior?**
Run angular4 universal app with CLI via ts-node

* **Angular version:** 4.2.3

* **Browser:** all
 
* **Language:** TypeScript 2.3.4

* **Node (for AoT issues):** `node --version` =   v6.11.0

**Comment by fulls1z3** [comment]
@maosmurf this project is aimed to be used in conjunction with `awesome-typescript-loader` and `@ngtools/webpack` on webpack bundler. Providing `ts-node` support is insurmountable at the moment.

If you could come up with some PR, then we can discuss the implementation (*as well as on other projects*).
