### ISSUE TITLE
how to invalidate the cache?

### ISSUE THREAD

**Issue by paulogr** [ngx-universal/state-transfer#11]
I took a look at your code and can't figure out your policy for cache invalidation.

Could someone help me with this question?

Thank you.

**Comment by fulls1z3** [comment]
> There are only two hard things in computer science: **cache invalidation** and naming things - **Phil Karlton**

Well, I think he was really right with those thoughts, however ngx-cache offers a mechanism to invalidate - at least remove items from the cache.

Simply, use the `remove(key: string | number, wild =false)` method to remove items. if you specity the `wild` parameter `true`, then ngx-cache will remove all items which begins with the `key` (*exactly works as the LIKE operator in SQL, with `%` on the right side*).

Feel free to discuss the issue further if the information above is not sufficient solving your problem.
