### ISSUE TITLE
multiple inject methods called

### ISSUE THREAD

**Issue by TroodoNmike** [ngx-universal/state-transfer#7]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x] feature request
```

Great work on this repo. Congrats!

I have a use case where I am setting data via stateTransfer.set('key', 'data'); in two different services. However I will not know which one finishes first so i have to use stateTransfer.inject(); in both of them. This injects method at the end creates two versions of <script> in the output which is not ideal. Is is possible to modify inject(); method so that it appends data to the existing code? What do you think?

**Comment by crebuh** [comment]
@TroodoNmike 

I've the same issue and I'm searching for a solution.
