### ISSUE TITLE
state-transfer service requests cached with `empty` params key

### ISSUE THREAD

**Issue by ChrisDalley** [ngx-universal/state-transfer#8]
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
When using the Http Transfer Service to cache a HTTP request which uses RequestOptions with URLSearchParams, the key generated for the state cache comprises of the request URL and an empty request options. This causes the same response to get stored for any requests made to the same url with different search params. 

**Expected/desired behavior**
URLSearchParams should be included in the key generated for the state map, different search params to the same URL should have different responses stored in the state. 

**Minimal reproduction of the problem with instructions**
```
const params: URLSearchParams = new URLSearchParams();
params.set('_embed', 'true');
params.set('per_page', 10);
let options = new RequestOptions();
options.params = params;

return this.httpTransferService.get( "https://api.test.com", options).map( data => {
   // Do something with the data
});
```
Will be stored in the state-transfer service store as 
```
key: "https://api.test.com{\"search\":{\"rawParams\":\"\",\"queryEncoder\":{},\"paramsMap\":{}}}",
value: response
```

Seems to be when you run JSON.stringify on the URLSearchParams, the params map value gets emptied. 

**What is the motivation / use case for changing the behavior?**
To be able to use multiple seperate api requests to the same url

* **Angular version:** 2.0
   Angular Version ~4.1.3
    "@ngx-universal/config-loader": "~0.4.0-rc.1",
    "@ngx-universal/express-engine": "~0.4.0-beta.1",
    "@ngx-universal/state-transfer": "~0.4.0-beta.1",
    "@ngx-universal/translate-loader": "~0.4.0-beta.1",

**Comment by fulls1z3** [comment]
@ChrisDalley I'll have a look on it on the upcoming days/week and let you know about it.

**Comment by br-gailitis** [comment]
@ChrisDalley refactor your code to:

```
const params = {'_embed': true, 'per_page', 10};
return this.httpTransferService.get( "https://api.test.com", {params}).map( data => {
   // Do something with the data
});
```

Though not exactly the prescribed Angular way, it _will_ stringify properly.

**Side note:**  Another issue here its seems is the HttpTransferService has not switched to the new HttpClient (for Angular 4+) though I don't think JSON.stringify would work with the recommended set up for the new client either.
