### ISSUE TITLE
dependency on compiler

### ISSUE THREAD

**Issue by dipunm** [ngx-universal/state-transfer#9]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

Add the following line into your AppModule
`import { BrowserStateTransferModule } from '@ngx-universal/state-transfer';`

**Expected/desired behavior**

This file imports the ServerStateTransferModule which in turn imports `@angular/platform-server`.
Desired: The project should not be dependant on `@angular/platform-server` because of the above steps

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

By importing the server platform, the client script grows from less than 800kb to 4mb. Also, the compiler is included even though the client script is aot compiled.

**Please tell us about your environment:**

* **Angular version:** 4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v7.8.0

**Comment by hmagrini** [comment]
I was just about to report the same issue. Here are some repro steps:
* create clean repo `ng new compiler-bug --skip-git`
* add minimal deps `yarn add webpack-bundle-analyzer @angular/platform-server @ngx-universal/state-transfer`
* run build to test that AOT should net a `vendor.js` ~850 kB and doesn't include `angular/compiler` :  `ng build --prod --stats-json && ./node_modules/.bin/webpack-bundle-analyzer ./dist/stats.json`. 
* add any of the modules from `ngx-universal/state-transfer`:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { HttpTransferModule } from '@ngx-universal/state-transfer';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpTransferModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
* run build with cmd from above, now `vendor.js` is ~2.84 MB

**Comment by fulls1z3** [comment]
Hi folks, sorry for replying late I'll be checking the issue to generate a possible solution soon (*upcoming holidays*).

**Comment by hmagrini** [comment]
@fulls1z3 Hi there! any update on this? I'm more than happy to take a crack on this if pointed in the right direction 👍

**Comment by fulls1z3** [comment]
@dipunm @hermagrini I'm on it now 🤔

**Comment by fulls1z3** [comment]
@dipunm @hermagrini well, I had a look on the source files, and confirmed that there's a direct dependency to `@angular/platform-server`, we use it to retrieve the document according to `Universal Gotcha`s, as below:

```typescript
import { PlatformState } from '@angular/platform-server';
...
constructor(@Inject(STATE_ID) private readonly stateId: string,
              private readonly platformState: PlatformState,
...
const document: any = this.platformState.getDocument();
```

If someone has a better idea at this point, please don't hesitate to share with me.

**Comment by fulls1z3** [comment]
@theomathieubhvr as I mentioned you on https://github.com/ng-seed/universal/issues/43, this issue might also give you some hints.

**Comment by dipunm** [comment]
I just checked it out and had a look. I made some changes, but I have no idea how to test it. I installed karma, but it complains that there is no karma.config file in the config folder.

Reckon I should do a PR anyway?

**Comment by fulls1z3** [comment]
@dipunm you can upload right here at the topic in a zip file

**Comment by dipunm** [comment]
[Archive.zip](https://github.com/ngx-universal/state-transfer/files/1196996/Archive.zip)
Here it is

**Comment by dipunm** [comment]
any thoughts on the zip?

**Comment by fulls1z3** [comment]
@dipunm I'm working on a general update on all repos - it means a tremendous amount of issues will be resolved, and I'll analyze (*highly probable implement*) the changes in that zip file.
